export const API_URL = "http://localhost:4000";

export const partTypes = [
  { label: "Case", name: "cases" },
  { label: "Cpu Coolers", name: "cpucoolers" },
  { label: "Cpu", name: "cpu" },
  { label: "Ram", name: "memory" },
  { label: "Motherboard", name: "motherboard" },
  { label: "Videocard", name: "videocard" },
  { label: "Storage", name: "storage" },
  { label: "Power Supply", name: "powersupply" },
];

export const possibleKeys = [
  "price",
  "display_name",
  "size",
  "type",
  "socket_support",
  "additional",
  "lithography",
  "tdp",
  "cores_count",
  "threads_count",
  "cores_frequency_max",
  "cores_frequency_nominal",
  "memory_frequency_max",
  "memory_type",
  "video_core_model",
  "gpu_cores_count",
  "gpu_frequency",
  "socket",
  "frequency",
  "modules_number",
  "timing ",
  "chipset",
  "ram_max",
  "lineup",
  "memory",
  "chip",
  "memory_frequency",
  "core_frequency",
  "interface",
  "capacity",
  "form_factor",
  "bandwidth",
  "write_speed",
  "reading_speed",
  "power",
];

export const isMockData = false;
